on:
  push:
    branches: develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: .
        remote: /var/www/html
        host: ${{ secrets.TEST_HOST }}
        port: ${{ secrets.TEST_PORT}}
        username: ${{ secrets.TEST_USERNAME }}
        password: ${{ secrets.TEST_PASSWORD }}        
