on:
  push:
    branches: develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Must checkout first, otherwise would get empty folder, see https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # Modify `master` to valid version, from https://github.com/marketplace/actions/action-rsync
      - uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.TEST_HOST }}
          KEY: ${{ secrets.TEST_SSH_KEY }}
          TARGET: /var/www/html/       
